import { Geist, Inter, Montserrat,Geist_Mono } from "next/font/google";
import { 
  ClerkProvider, 
  SignInButton, 
  SignedIn, 
  SignedOut, 
  UserButton
} from '@clerk/nextjs';
import "./globals.css";
import Header from "@/components/Header";

const inter = Montserrat ({ subsets: ['latin'] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
